# These are supported funding model platforms

# github: [theExtraTerrestrial]  # Uncomment if you want GitHub Sponsors
# ko_fi: username                # Uncomment if you have Ko-fi
# patreon: username              # Uncomment if you have Patreon
# custom: ['https://your-funding-link.com']  # Custom funding links
